version: '3.1'

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    volumes: 
      - ./search_data:/usr/share/elasticsearch/data

  db:
    image: mysql:5.7.27
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mysql:/var/lib/mysql
      
  rails:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: sotldirectory
    restart: always
    environment:
      - SECRET_KEY_BASE=e9f0887b29e854a81e8dbdb3090b9a1b54ba2201c41b52966df6100ce672a70ed6c4c1a029ccb28cfc162a52ae2e68543b675eb5d4b703ecee903ebd8d66a6bb     
      - DATABASE_PASSWORD=docker
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TERM=xterm
    #  - RAILS_ENV=production # uncomment for production
    # Required to Import Support Doc Files From Digital Measures
    # - DMEASURES_URL
    # - DMEASURES_USER
    # - DMEASURES_PW

    volumes:
      - .:/home/sotldirectory
    ports:
      - "3000:3000"
      - "3001:3001"      
    links:
      - elasticsearch      
      - db
  #     - selenium # development only
  
  # selenium:
  #   image: selenium/standalone-chrome-debug
  #   container_name: selenium
  #   privileged: true
  #   ports:
  #     - '4444:4444'
  #     - '5900:5900'
  #   environment:
  #     - SCREEN_WIDTH=1440
  #     - SCREEN_HEIGHT=900
  #     - VNC_NO_PASSWORD=true
  #   logging:
  #     driver: none


